module.exports.routes = {
  '/': {view: 'pages/Home'},
  'GET /Anmelden': {view: 'pages/Login'},
  'GET /Admin': {action: 'view-admin'},
  'GET /Suche': {action: 'view-all-products'},
  'GET /Home': {view: 'pages/Home'},
  'GET /UeberUns': {view: 'pages/UeberUns'},
  'GET /Impressum': {view: 'pages/impressum'},
  'GET /Ordered': {view: 'pages/Ordered'},
  'GET /Profil': {action: 'account/view-account-overview'},
  'GET /Profil/benutzer': {action: 'account/view-edit-profile'},
  'GET /Profil/passwort': {action: 'account/view-edit-password'},
  'GET /carbrand': {controller: 'CarBrandController', action: 'find'},
  'GET /carmodel': {controller: 'CarModelController', action: 'find'},
  'GET /category': {controller: 'CategoryController', action: 'find'},
  'GET /products': {controller: 'ProductController', action: 'find'},
  'GET /carbrand/new': {controller: 'CarBrandController', action: 'new'},
  'POST /carbrand': {controller: 'CarBrandController', action: 'create'},
  'GET /carbrand/:id/destroy': {
    controller: 'CarBrandController',
    action: 'destroy',
  },
  'GET /carmodel/new': {controller: 'CarModelController', action: 'new'},
  'POST /carmodel': {controller: 'CarModelController', action: 'create'},
  'GET /carmodel/:id/destroy': {
    controller: 'CarModelController',
    action: 'destroyEachModel',
  },
  'GET /category/new': {controller: 'CategoryController', action: 'new'},
  'POST /category': {controller: 'CategoryController', action: 'create'},
  'GET /category/:id/destroy': {
    controller: 'CategoryController',
    action: 'destroyOne',
  },
  'GET /products/new': {controller: 'ProductController', action: 'new'},
  'POST /products': {controller: 'ProductController', action: 'create'},
  'GET /products/:id/destroy': {
    controller: 'ProductController',
    action: 'destroyOne',
  },
  'GET /products/:id': {controller: 'ProductController', action: 'findOne'},
  'GET /products/:id/edit': {
    controller: 'ProductController',
    action: 'editOne',
  },
  'POST /products/:id/update': {
    controller: 'ProductController',
    action: 'updateOne',
  },
  'GET /products/:id/uploadImageForm': {
    controller: 'ProductController',
    action: 'uploadImageForm',
  },
  'POST /products/:id/uploadImage': {
    controller: 'ProductController',
    action: 'uploadImage',
  },
  'GET   /Abmelden': {action: 'account/logout'},
  'POST  /login': {action: 'entrance/login'},
  'POST  /signup': {action: 'entrance/signup'},
  'POST  /updateProfile': {action: 'account/update-profile'},
  'POST  /updatePassword': {action: 'account/update-password'},
  'GET   /Registrieren': {action: 'entrance/view-signup'},
  'GET /api/product': {action: 'api/product/index'},
  'GET /api/basket': {action: 'api/basket/get'},
  'DELETE /api/basket': {action: 'api/basket/remove'},
  'POST /api/basket': {action: 'api/basket/add'},
};
